### ISSUE TITLE
ST3 - Not responding

### ISSUE THREAD

**Issue by ppGrande** [gwenzek/SublimeSetWindowTitle#3] opened 2017-12-27 14:46 UTC
Sublime Text 3 , Windows 8.1

Just creating a folder like
C:\Users\{myUserName}\AppData\Roaming\Sublime Text 3\Packages\set_window_title

Download and copy both source files inside

restart ST3, it seems to change the tile, but it also froze ST3, not being able to do anything else than closing (by force) ST3

disable (renamed extension os py file) and works again, re-anable the file, and fails again

not sure if has been tested properly on ST3 on windows

**Comment by gwenzek** [comment] 2017-12-27 15:37
Thanks for reporting.
Note that the plugin is not available on Package Control for Windows because of this issue.
I don't have access to a Windows PC so I can't properly test it on this platform.

According to @cjdoris the crash on Windows appears when trying to rename the windows on the `plugin_loaded` event.
I wanted to look into the root cause and provide a valid fix for this, but I didn't found time,
so I just pushed a quick hack: disable the `plugin_loaded` event for Windows.

Can you try to pull the latest commits and confirm that ST is not crashing anymore and that windows get renamed when selecting them ?

Any help on the `user32` API or ideas on how to debug the plugin is welcome. It's maybe just an offset error, or Windows waiting for the plugin to release a handle or something like that.

**Comment by ppGrande** [comment] 2017-12-27 16:28
Thanks a lot,

yes, I comment the next two lines, and things went ok 
```
#  for window in sublime.windows():
#    title_setter.run(window.active_view())
```

there seems thre is still some issue with view in some cases is null (as when opening the window to open a new proyect)
Console screams : 
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "C:\Users\{myUser}\AppData\Roaming\Sublime Text 3\Packages\set_window_title\set_window_title.py", line 102, in on_activated_async
    self.run(view)
  File "C:\Users\{myUser}\AppData\Roaming\Sublime Text 3\Packages\set_window_title\set_window_title.py", line 123, in run
    self.rename_window_windows(view.window(), official_title, new_title)
  File "C:\Users\{myUser}\AppData\Roaming\Sublime Text 3\Packages\set_window_title\set_window_title.py", line 228, in rename_window_windows
    w = self.window_handle_cache.get(window.id(), None)
AttributeError: 'NoneType' object has no attribute 'id'
```

But otherwise this "warning" things seems to go ok

**Comment by ppGrande** [comment] 2017-12-27 17:31
Little bug I found, you may want correct as I guess will be easy
New file (CRTL + N), opens with nice window title, as you start writing ST takes over the control and start writing the window title, (so no nice window title)

it is just a temporary thing, as soon as you switch from tab or window, it cleans and nice title shows again

**Closed as completed** 2018-01-03 17:43 UTC
